Progreso1Proyecto_M.E__F.V/Controllers/Registro_MController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Progreso1Proyecto_M.E__F.V.Data;
using Progreso1Proyecto_M.E__F.V.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Progreso1Proyecto_M.E__F.V.Controllers
{
    public class Registro_MController : Controller
    {
        private readonly Progreso1Proyecto_ME__FVContext _context;

        Log logger = Log.Instance;

        public Registro_MController(Progreso1Proyecto_ME__FVContext context)
        {
            _context = context;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // Cerrar el archivo de registro
                logger.CloseLogFile();
            }
            base.Dispose(disposing);
        }

        public class LogActionFilter : ActionFilterAttribute
        {
            public override void OnActionExecuted(ActionExecutedContext context)
            {
                Log logger = Log.Instance;
                logger.CloseLogFile();
                base.OnActionExecuted(context);
            }
        }

        // GET: Registro_M
        public async Task<IActionResult> Index(string buscar, int filtro)
        {
            var registro_M = from Registro_M in _context.Registro_M select Registro_M;

            if (!String.IsNullOrEmpty(buscar))
            {
                registro_M = registro_M.Where(s => s.Materia!.Contains(buscar));
            }

            if (filtro != 0)
            {
                registro_M = registro_M.Where(s => s.Calificacion == filtro);
                ViewData["FiltroCalificacion"] = filtro;
            }
            else
            {
                ViewData["FiltroCalificacion"] = null;
            }
            registro_M = registro_M.OrderByDescending(s => s.Calificacion);

            return View(await registro_M.ToListAsync());
        }

        // GET: Registro_M/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Registro_M == null)
            {
                return NotFound();
            }

            var registro_M = await _context.Registro_M
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registro_M == null)
            {
                return NotFound();
            }

            return View(registro_M);
        }

        [Authorize]
        // GET: Registro_M/Create
        public IActionResult Create()
        {
            logger.LogButtonClick("Crear");
            return View();
        }

        // POST: Registro_M/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Semestre,Materia,Profesor,Calificacion,Descripcion,Cualidad,Horario")] Registro_M registro_M)
        {
            logger.LogButtonClick("Registrar");
            if (ModelState.IsValid)
            {
                _context.Add(registro_M);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registro_M);
        }

        // GET: Registro_M/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            logger.LogButtonClick("Editar");
            if (id == null || _context.Registro_M == null)
            {
                return NotFound();
            }

            var registro_M = await _context.Registro_M.FindAsync(id);
            if (registro_M == null)
            {
                return NotFound();
            }
            return View(registro_M);
        }

        // POST: Registro_M/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Semestre,Materia,Profesor,Calificacion,Descripcion,Cualidad,Horario")] Registro_M registro_M)
        {
            logger.LogButtonClick("Editar");
            if (id != registro_M.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registro_M);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Registro_MExists(registro_M.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registro_M);
        }

        [Authorize]
        // GET: Registro_M/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            logger.LogButtonClick("Borrar");
            if (id == null || _context.Registro_M == null)
            {
                return NotFound();
            }

            var registro_M = await _context.Registro_M
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registro_M == null)
            {
                return NotFound();
            }

            return View(registro_M);
        }

        // POST: Registro_M/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            logger.LogButtonClick("Borrar");
            if (_context.Registro_M == null)
            {
                return Problem("Entity set 'Progreso1Proyecto_ME__FVContext.Registro_M' is null.");
            }
            var registro_M = await _context.Registro_M.FindAsync(id);
            if (registro_M != null)
            {
                _context.Registro_M.Remove(registro_M);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Registro_MExists(int id)
        {
            return (_context.Registro_M?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Progreso1Proyecto_M.E__F.V/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Progreso1Proyecto_M.E__F.V</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Progreso1Proyecto_M.E__F.V.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-toggleable navbar-dark bg-dark border-bottom- box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HELP STUDENTS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Para que?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Nuestros Objetivos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Registro_M" asp-action="Index">Mejores Recomendaciones en profesores</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark ">
        <div class="container">
            <center>Espero seamos de ayuda para ti. Te deseo el mejor semestre de tu carrera :) </center>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>